### ISSUE TITLE
File path is not part of fmridenoise valid pipelines

### ISSUE THREAD

**Issue by zone009** [compneuro-ncu/fmridenoise#49]
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-c_373mzu/fmridenoise/setup.py", line 4, in <module>
        from fmridenoise.pipelines import get_pipelines_paths
      File "/tmp/pip-build-c_373mzu/fmridenoise/fmridenoise/pipelines/__init__.py", line 10
        raise ValueError(f"File '{path}' is not part of fmridenoise valid pipelines!")
                                                                                    ^
    SyntaxError: invalid syntax

ubuntu 18.04 64bit

**Comment by SiegfriedWagner** [comment]
What is your fmridenoise configuration - Is it from pip or git and what are your input parameters?
