### ISSUE TITLE
Using numbers as run identifiers will result in error

### ISSUE THREAD

**Issue by BotondA** [compneuro-ncu/fmridenoise#65]
I'm using the dev branch of fmridenoise. I tried running it for two subjects as a test, but it looks like some component won't be able to properly interpret numbers as run identifiers. I currently have two runs: run-1 and run-2. I tried renaming everything to run-01 and run-02 but it would result in the same output. Here's the complete output below:

```
(venv) (base) ben@pascal:~/apps/fmridenoise_dev/testing$ fmridenoise compare /home/ben/apps/fmridenoise_dev/testing
201129-23:21:44,665 nipype.workflow INFO:
	 [Node] Setting-up "BidsValidate" in "/tmp/tmp3qb9buw1/BidsValidate".
201129-23:21:44,670 nipype.workflow INFO:
	 [Node] Running "BidsValidate" ("fmridenoise.interfaces.bids.BIDSValidate")
/home/ben/apps/fmridenoise_dev/venv/lib/python3.7/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
/home/ben/apps/fmridenoise_dev/venv/lib/python3.7/site-packages/bids/layout/models.py:152: FutureWarning: The 'extension' entity currently excludes the leading dot ('.'). As of version 0.14.0, it will include the leading dot. To suppress this warning and include the leading dot, use `bids.config.set_option('extension_initial_dot', True)`.
  FutureWarning)
201129-23:22:00,892 nipype.workflow WARNING:
	 Storing result file without outputs
201129-23:22:00,893 nipype.workflow WARNING:
	 [Node] Error on "BidsValidate" (/tmp/tmp3qb9buw1/BidsValidate)
Traceback (most recent call last):
  File "/home/ben/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ben/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ben/apps/fmridenoise_dev/fmridenoise/fmridenoise/__main__.py", line 218, in <module>
    main()
  File "/home/ben/apps/fmridenoise_dev/fmridenoise/fmridenoise/__main__.py", line 210, in main
    compare(args)
  File "/home/ben/apps/fmridenoise_dev/fmridenoise/fmridenoise/__main__.py", line 174, in compare
    low_pass=args.low_pass)
  File "/home/ben/apps/fmridenoise_dev/fmridenoise/fmridenoise/workflows/base.py", line 431, in init_fmridenoise_wf
    result = bids_validate.run()
  File "/home/ben/apps/fmridenoise_dev/venv/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/home/ben/apps/fmridenoise_dev/venv/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/home/ben/apps/fmridenoise_dev/venv/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/ben/apps/fmridenoise_dev/venv/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 436, in run
    outputs = self.aggregate_outputs(runtime)
  File "/home/ben/apps/fmridenoise_dev/venv/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 545, in aggregate_outputs
    raise error
  File "/home/ben/apps/fmridenoise_dev/venv/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 537, in aggregate_outputs
    setattr(outputs, key, val)
  File "/home/ben/apps/fmridenoise_dev/venv/lib/python3.7/site-packages/traits/trait_types.py", line 2473, in validate
    return TraitListObject(self, object, name, value)
  File "/home/ben/apps/fmridenoise_dev/venv/lib/python3.7/site-packages/traits/trait_list_object.py", line 582, in __init__
    notifiers=[self.notifier],
  File "/home/ben/apps/fmridenoise_dev/venv/lib/python3.7/site-packages/traits/trait_list_object.py", line 210, in __init__
    super().__init__(self.item_validator(item) for item in iterable)
  File "/home/ben/apps/fmridenoise_dev/venv/lib/python3.7/site-packages/traits/trait_list_object.py", line 210, in <genexpr>
    super().__init__(self.item_validator(item) for item in iterable)
  File "/home/ben/apps/fmridenoise_dev/venv/lib/python3.7/site-packages/traits/trait_list_object.py", line 862, in _item_validator
    return trait_validator(object, self.name, value)
  File "/home/ben/apps/fmridenoise_dev/venv/lib/python3.7/site-packages/traits/trait_types.py", line 348, in validate
    self.error(object, name, value)
  File "/home/ben/apps/fmridenoise_dev/venv/lib/python3.7/site-packages/traits/base_trait_handler.py", line 75, in error
    object, name, self.full_info(object, name, value), value
traits.trait_errors.TraitError: Each element of the 'runs' trait of a BIDSValidateOutputSpec instance must be a string, but a value of 1 <class 'int'> was specified.
```

**Comment by SiegfriedWagner** [comment]
I made changes that should assure proper types of inputs for worklflow.
https://github.com/compneuro-ncu/fmridenoise/commit/ad581576350025d7ecde654c32a430451d6d90da

**Comment by SiegfriedWagner** [comment]
There was BIDS standard misunderstanding from my side. Runs are indexed and not labeled in standard (which means that their proper type is int not str). I made changes to properly address this issue in https://github.com/compneuro-ncu/fmridenoise/commit/682f4464730363c6a39e3539a1bcaefd197a2a25. Could you check if fmridenoise crashes on your input?

**Comment by BotondA** [comment]
Looks like this fixed it. fmridenoise (dev branch) now runs on my system without crashing. Thank you!
