### ISSUE TITLE
bids.exceptions.BIDSDerivativesValidationError: Every valid BIDS-derivatives dataset must have a PipelineDescription.Name field set inside 'dataset_description.json'.

### ISSUE THREAD

**Issue by SiegfriedWagner** [compneuro-ncu/fmridenoise#78]
```
/home/siegfriedwagner/virtual_enviroments/fmridenoise/bin/python -m fmridenoise compare /home/siegfriedwagner/Downloads/fmriprep_dummy/dummy -d fmriprep
201219-16:29:17,747 nipype.workflow INFO:
	 [Node] Setting-up "BidsValidate" in "/tmp/tmprm8sxop8/BidsValidate".
201219-16:29:17,749 nipype.workflow INFO:
	 [Node] Running "BidsValidate" ("fmridenoise.interfaces.bids.BIDSValidate")
201219-16:29:19,805 nipype.workflow WARNING:
	 Storing result file without outputs
201219-16:29:19,805 nipype.workflow WARNING:
	 [Node] Error on "BidsValidate" (/tmp/tmprm8sxop8/BidsValidate)
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/siegfriedwagner/git/fmridenoise/fmridenoise/__main__.py", line 236, in <module>
    main()
  File "/home/siegfriedwagner/git/fmridenoise/fmridenoise/__main__.py", line 228, in main
    compare(args)
  File "/home/siegfriedwagner/git/fmridenoise/fmridenoise/__main__.py", line 177, in compare
    workflow = init_fmridenoise_wf(input_dir,
  File "/home/siegfriedwagner/git/fmridenoise/fmridenoise/workflows/base.py", line 455, in init_fmridenoise_wf
    result = bids_validate.run()
  File "/home/siegfriedwagner/virtual_enviroments/fmridenoise/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/home/siegfriedwagner/virtual_enviroments/fmridenoise/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/home/siegfriedwagner/virtual_enviroments/fmridenoise/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/siegfriedwagner/virtual_enviroments/fmridenoise/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 434, in run
    runtime = self._run_interface(runtime)
  File "/home/siegfriedwagner/git/fmridenoise/fmridenoise/interfaces/bids.py", line 387, in _run_interface
    layout = BIDSLayout(
  File "/home/siegfriedwagner/virtual_enviroments/fmridenoise/lib/python3.8/site-packages/bids/layout/layout.py", line 161, in __init__
    self.add_derivatives(
  File "/home/siegfriedwagner/virtual_enviroments/fmridenoise/lib/python3.8/site-packages/bids/layout/layout.py", line 469, in add_derivatives
    deriv_paths = validate_derivative_paths(paths, self, **kwargs)
  File "/home/siegfriedwagner/virtual_enviroments/fmridenoise/lib/python3.8/site-packages/bids/layout/validation.py", line 138, in validate_derivative_paths
    raise BIDSDerivativesValidationError(
bids.exceptions.BIDSDerivativesValidationError: Every valid BIDS-derivatives dataset must have a PipelineDescription.Name field set inside 'dataset_description.json'. 
Example: {'PipelineDescription': {'Name': 'Example pipeline'}}

Process finished with exit code 1
```
Problem is connected (partialy) with another resolved issue https://github.com/compneuro-ncu/fmridenoise/issues/74
This problem is still present, but now not in our project but in a roots of pybids.
https://github.com/bids-standard/pybids/issues/640

For now I will recommend not using datasets in BIDS 1.4 standard because there are no tools to interact with it  

Until this problem is resolved in pybids it will be hard to support latest BIDS standard

**Comment by neurosurd** [comment]
Hi,
Was this issue resolved? When i ran fmridenoise with default options, i received the following error

`bids.exceptions.BIDSDerivativesValidationError: Every valid BIDS-derivatives dataset must have a PipelineDescription.Name field set inside 'dataset_description.json'. 
Example: {'PipelineDescription': {'Name': 'Example pipeline'}}`

As per suggestions, i modified the dataset_description.json in my bids derivates/fmriprep folder (See attached)
[dataset_description.json.txt](https://github.com/compneuro-ncu/fmridenoise/files/6964704/dataset_description.json.txt)

But now im getting the following error ( see attached) 
[dataset_desc_error.txt](https://github.com/compneuro-ncu/fmridenoise/files/6964724/dataset_desc_error.txt)

Please advise. Thanks
