### ISSUE TITLE
problems installing fmridenoise

### ISSUE THREAD

**Issue by atkinsonap** [compneuro-ncu/fmridenoise#87]
Hello,

I'm unable to install fmridenoise on my Mac (OS Mojave, with the preinstalled Python 2 and the latest installation of Python 3.9). I've tried several ways:

1. Via Terminal (bash), with commands
(a) pip install fmridenoise
(b) python3 -m pip install fmridenoise

2. Downloaded the latest version of fmridenoise from github, unzipped it, cd in Terminal to the downloaded location, and enter following command in Terminal: python setup.py install.

The respective error messages are below. I'd be grateful for your help.

-----

Both 1(a) and 1(b) give the following error message:

    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/fw/l5xdrbkd7m93pk1_r2hkzfx40000gn/T/pip-install-ojcjdsoo/fmridenoise_d93b800b0d4641e396e6a1d99445df6d/setup.py'"'"'; __file__='"'"'/private/var/folders/fw/l5xdrbkd7m93pk1_r2hkzfx40000gn/T/pip-install-ojcjdsoo/fmridenoise_d93b800b0d4641e396e6a1d99445df6d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/fw/l5xdrbkd7m93pk1_r2hkzfx40000gn/T/pip-pip-egg-info-3xw5zobi
         cwd: /private/var/folders/fw/l5xdrbkd7m93pk1_r2hkzfx40000gn/T/pip-install-ojcjdsoo/fmridenoise_d93b800b0d4641e396e6a1d99445df6d/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/fw/l5xdrbkd7m93pk1_r2hkzfx40000gn/T/pip-install-ojcjdsoo/fmridenoise_d93b800b0d4641e396e6a1d99445df6d/setup.py", line 8, in <module>
        with open(join(__dir_path, "requirements.txt"), 'r') as fh:
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/fw/l5xdrbkd7m93pk1_r2hkzfx40000gn/T/pip-install-ojcjdsoo/fmridenoise_d93b800b0d4641e396e6a1d99445df6d/requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

------

Option 2 gave me the following error:

Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    import versioneer
  File "/Users/Atkinson/fmridenoise-0.2.0/versioneer.py", line 1739
    file=sys.stderr)
        ^
SyntaxError: invalid syntax

**Comment by SiegfriedWagner** [comment]
I will address it tomorrow. For now it looks like I haven't put ```requirements.txt``` in ```MANIFEST.in```.

**Comment by atkinsonap** [comment]
Hello,

Thanks very much.

Another thing I noticed: one of the requirements is numpy<1.16.5,>=1.11. But the latest version of numpy, which I have installed, is v1.19.0. Can fmridenoise run with this more recent version of numpy or do I need to install an older version?

Regards,

Anthony

**Comment by SiegfriedWagner** [comment]
I acknowledged both you suggestions and included them in version 0.2.1.
Please check if everything is working now, if everything is fine we can close this issue. 
Btw. I wonder how is our software running on Mac - we had no access to any, so some platform dependent bugs may occur.

**Comment by atkinsonap** [comment]
That’s great, thanks very much.

The installation seems to have worked — I got the 'Successfully installed fmridenoise-0.2.1' at the end of the installation.

But I can’t seem to run it. I just get the following error:

-bash: /Library/Frameworks/Python.framework/Versions/3.9/bin/fmridenoise: /usr/bin/sh: bad interpreter: No such file or directory

I’ve done a quick google search and I think the problem is that my system's sh interpreter is at /bin/sh rather than at /usr/bin/sh 

If there’s a solution I can make at my end, then I’m happy to try what you recommend.

Thanks,

Anthony

**Comment by SiegfriedWagner** [comment]
```fmridenoise``` console command is just calling this file https://github.com/compneuro-ncu/fmridenoise/blob/master/fmridenoise/scripts/fmridenoise - shebang is not suitable for mac (and for windows too)
for now you can just get access to fmridenoise by calling ```python -O -m fmridenoise``` - it should work as calling the script. 
I will change it in next minor release from ```/usr/bin/sh``` to ```/bin/sh```.

**Comment by atkinsonap** [comment]
Thanks Siegfried. I got it running OK with that command (after changing python to python3). 'fmridenoise compare' ran through all the subjects I specified, but there were some errors along the way and the group report was not produced. Attached are the 4 crash report files. I haven't managed to work out whether the problem is in the code and/or at my end. Could you please look into this when you get the chance?

Thanks,

Anthony

________________________________
