### ISSUE TITLE
Problem running fmridenoise: Missing files

### ISSUE THREAD

**Issue by QKmeans0902** [compneuro-ncu/fmridenoise#93]
Hello all,

I met problems when running fmridenoise on data preprocessed by fmriprep:

`fmridenoise compare /media/ziyu/Kun_SSD/Dep/ -sub Dep001 -p pipeline-Null`

My bids_dir is /media/ziyu/Kun_SSD/Dep/ and I just used null pipeline to see whether it could work well, but I got this:

```
210216-20:21:43,384 nipype.workflow INFO:
	 [Node] Setting-up "BidsValidate" in "/tmp/tmpw41_acm0/BidsValidate".
210216-20:21:43,393 nipype.workflow INFO:
	 [Node] Running "BidsValidate" ("fmridenoise.interfaces.bids.BIDSValidate")
210216-20:22:55,299 nipype.workflow WARNING:
	 Storing result file without outputs
210216-20:22:55,301 nipype.workflow WARNING:
	 [Node] Error on "BidsValidate" (/tmp/tmpw41_acm0/BidsValidate)
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ziyu/.local/lib/python3.8/site-packages/fmridenoise/__main__.py", line 238, in <module>
    main()
  File "/home/ziyu/.local/lib/python3.8/site-packages/fmridenoise/__main__.py", line 230, in main
    compare(args)
  File "/home/ziyu/.local/lib/python3.8/site-packages/fmridenoise/__main__.py", line 179, in compare
    workflow = init_fmridenoise_wf(input_dir,
  File "/home/ziyu/.local/lib/python3.8/site-packages/fmridenoise/workflows/base.py", line 455, in init_fmridenoise_wf
    result = bids_validate.run()
  File "/home/ziyu/.local/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/home/ziyu/.local/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/home/ziyu/.local/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/ziyu/.local/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 434, in run
    runtime = self._run_interface(runtime)
  File "/home/ziyu/.local/lib/python3.8/site-packages/fmridenoise/interfaces/bids.py", line 408, in _run_interface
    entities_files, (tasks, sessions, subjects, runs) = BIDSValidate.validate_files(
  File "/home/ziyu/.local/lib/python3.8/site-packages/fmridenoise/interfaces/bids.py", line 361, in validate_files
    raise MissingFile(
fmridenoise.interfaces.bids.MissingFile: missing file(s) for {'subject': 'Dep001', 'task': 'rest', 'extension': ['nii', 'nii.gz'], 'suffix': 'bold', 'desc': 'preproc', 'space': 'MNI152NLin2009cAsym'} (check if you are using AROMA pipelines)
```

I am confused about this. I do have the file sub-Dep001_task-rest_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz. And I do have its json file as well as confounds' tsv and json files. I am not clear how this happens.

Data was preprocessed by fmriprep 20.2.1. OS is Ubuntu 20. Image files have full write, read and execution permissions, and it just happens. I would be grateful for tell me what's wrong with this.

**Comment by nastia-lado** [comment]
Hi!

I have a very similar issue.
If I run only `fmridenoise compare <bids_dir>` everything executes correctly, I get outputs for single subjects, however I don't get a group report.
But if I try to specify session or subject I get an error `fmridenoise.interfaces.bids.MissingFile: missing file(s) for {'subject': 'sub-19', 'task': 'nback', 'session': 'ses-1', 'run': 1, 'extension': 'tsv', 'suffix': ['regressors', 'timeseries'], 'desc': 'confounds'} (check if you are using AROMA pipelines)`
even if I got an output for this subject with a previous command.

It's important for me because I have some of my subjects have only 2 sessions, and some of them 3. And if I don't specify any optional arguments for fmridenoise, subjects with 2 sessions are simply skipped, so I want to have the option to run them separately.

**Comment by strohkamp** [comment]
I had the same problem recently. It didn't occur, when giving the arguments as strings with quotation marks. Seems to be that simple. For the example  @QKmeans0902:
`fmridenoise compare /media/ziyu/Kun_SSD/Dep/ -sub "Dep001" -p "pipeline-Null" `
Same when giving a session `-ses "01"`
When giving multiple optional arguments they seem to need to be as such strings separated by spaces.
e.g.
`-sub "01" "02"....`
I think it would be quite beneficial giving an usage example in the docs.
