### ISSUE TITLE
MultiProc Issue

### ISSUE THREAD

**Issue by neurosurd** [compneuro-ncu/fmridenoise#98]
Hi
I was able to run fmridenoise on 3 subjects with and without --MultiProc option. WIth multiproc option  i do see multiple processes being run. However when i choose the --MultiProc option for an entire dataset of 40 subjects, it seems to be too much even for a 56 thread/384GB RAM machine. I've two questions:
1. Is there a way i can allocate specific resources per subject/ job? What is the default allocation?
2. Can i run a few subjects at a time with MultiProc option and then do a group quality metrics calculation after completion of all the subjects?
Thanks for this very useful software!

**Comment by neurosurd** [comment]
In the meantime, i ran the dataset without the multiproc option. However, it looks like it gave an error ( below)  at the final stage of merging quality metrics. no report was created. Any ideas??

```nipypecli crash crash-20210821-043404-user259-JoinQualityMeasuresOverPipeline.a1.a0-b3744807-7902-4f02-8e27-8cd7ab67433a.pklz 


File: /home/user259/Desktop/vert_data/crash-20210821-043404-user259-JoinQualityMeasuresOverPipeline.a1.a0-b3744807-7902-4f02-8e27-8cd7ab67433a.pklz
Node: fmridenoise_wf.JoinQualityMeasuresOverPipeline
Working directory: /home/user259/Desktop/vert_data/fmridenoise_tmp/fmridenoise_wf/_run_1/_task_rest/JoinQualityMeasuresOverPipeline


Node inputs:

corr_matrix_no_high_motion_plot = <undefined>
corr_matrix_no_high_motion_plotJ1 = /home/user259/Desktop/vert_data/fmridenoise_tmp/quality_measures/task-rest_run-1_pipeline-24HMP8PhysSpikeReg_desc-fcFdCorrMatrixNoHighMotion_plot.svg
corr_matrix_no_high_motion_plotJ2 = /home/user259/Desktop/vert_data/fmridenoise_tmp/quality_measures/task-rest_run-1_pipeline-ICAAROMA8Phys4GS_desc-fcFdCorrMatrixNoHighMotion_plot.svg
corr_matrix_no_high_motion_plotJ3 = /home/user259/Desktop/vert_data/fmridenoise_tmp/quality_measures/task-rest_run-1_pipeline-24HMPaCompCorSpikeReg_desc-fcFdCorrMatrixNoHighMotion_plot.svg
corr_matrix_no_high_motion_plotJ4 = /home/user259/Desktop/vert_data/fmridenoise_tmp/quality_measures/task-rest_run-1_pipeline-ICAAROMA8Phys_desc-fcFdCorrMatrixNoHighMotion_plot.svg
corr_matrix_no_high_motion_plotJ5 = /home/user259/Desktop/vert_data/fmridenoise_tmp/quality_measures/task-rest_run-1_pipeline-Null_desc-fcFdCorrMatrixNoHighMotion_plot.svg
corr_matrix_no_high_motion_plotJ6 = /home/user259/Desktop/vert_data/fmridenoise_tmp/quality_measures/task-rest_run-1_pipeline-24HMP8PhysSpikeReg4GS_desc-fcFdCorrMatrixNoHighMotion_plot.svg
corr_matrix_no_high_motion_plotJ7 = /home/user259/Desktop/vert_data/fmridenoise_tmp/quality_measures/task-rest_run-1_pipeline-24HMPaCompCorSpikeReg4GSR_desc-fcFdCorrMatrixNoHighMotion_plot.svg
corr_matrix_plot = <undefined>
corr_matrix_plotJ1 = /home/user259/Desktop/vert_data/fmridenoise_tmp/quality_measures/task-rest_run-1_pipeline-24HMP8PhysSpikeReg_desc-fcFdCorrMatrix_plot.svg
corr_matrix_plotJ2 = /home/user259/Desktop/vert_data/fmridenoise_tmp/quality_measures/task-rest_run-1_pipeline-ICAAROMA8Phys4GS_desc-fcFdCorrMatrix_plot.svg
corr_matrix_plotJ3 = /home/user259/Desktop/vert_data/fmridenoise_tmp/quality_measures/task-rest_run-1_pipeline-24HMPaCompCorSpikeReg_desc-fcFdCorrMatrix_plot.svg
corr_matrix_plotJ4 = /home/user259/Desktop/vert_data/fmridenoise_tmp/quality_measures/task-rest_run-1_pipeline-ICAAROMA8Phys_desc-fcFdCorrMatrix_plot.svg
corr_matrix_plotJ5 = /home/user259/Desktop/vert_data/fmridenoise_tmp/quality_measures/task-rest_run-1_pipeline-Null_desc-fcFdCorrMatrix_plot.svg
corr_matrix_plotJ6 = /home/user259/Desktop/vert_data/fmridenoise_tmp/quality_measures/task-rest_run-1_pipeline-24HMP8PhysSpikeReg4GS_desc-fcFdCorrMatrix_plot.svg
corr_matrix_plotJ7 = /home/user259/Desktop/vert_data/fmridenoise_tmp/quality_measures/task-rest_run-1_pipeline-24HMPaCompCorSpikeReg4GSR_desc-fcFdCorrMatrix_plot.svg
excluded_subjects = <undefined>
excluded_subjectsJ1 = ExcludedSubjects(pipeline_name='24HMP8PhysSpikeReg', task='rest', session=None, run=1, excluded={'CT004', 'CT012'})
excluded_subjectsJ2 = ExcludedSubjects(pipeline_name='ICAAROMA8Phys4GS', task='rest', session=None, run=1, excluded=set())
excluded_subjectsJ3 = ExcludedSubjects(pipeline_name='24HMPaCompCorSpikeReg', task='rest', session=None, run=1, excluded={'CT004', 'CT012'})
excluded_subjectsJ4 = ExcludedSubjects(pipeline_name='ICAAROMA8Phys', task='rest', session=None, run=1, excluded=set())
excluded_subjectsJ5 = ExcludedSubjects(pipeline_name='Null', task='rest', session=None, run=1, excluded=set())
excluded_subjectsJ6 = ExcludedSubjects(pipeline_name='24HMP8PhysSpikeReg4GS', task='rest', session=None, run=1, excluded={'CT004', 'CT012'})
excluded_subjectsJ7 = ExcludedSubjects(pipeline_name='24HMPaCompCorSpikeReg4GSR', task='rest', session=None, run=1, excluded={'CT004', 'CT012'})
warnings = <undefined>
warningsJ1 = <undefined>
warningsJ2 = <undefined>
warningsJ3 = <undefined>
warningsJ4 = <undefined>
warningsJ5 = <undefined>
warningsJ6 = <undefined>
warningsJ7 = <undefined>



Traceback: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nipype/pipeline/plugins/linear.py", line 45, in run
    node.run(updatehash=updatehash)
  File "/usr/local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 1004, in _run_command
    return super(JoinNode, self)._run_command(execute, copyfiles)
  File "/usr/local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 430, in run
    outputs = self.aggregate_outputs(runtime)
  File "/usr/local/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 506, in aggregate_outputs
    predicted_outputs = self._list_outputs()  # Predictions from _list_outputs
  File "/usr/local/lib/python3.6/site-packages/fmridenoise-0+unknown-py3.6.egg/fmridenoise/interfaces/utility.py", line 21, in _list_outputs
    outputs[key] = list(chain(*outputs[key]))
TypeError: '_Undefined' object is not iterable
```
